### ISSUE TITLE
How to cite this dataset

### ISSUE THREAD

**Issue by gongpx20069** [fengxudi/mmWave-gesture-dataset#2]
Thank you for your generous sharing! 
Is there a paper related to this dataset so that I can cite it ?

Thanks for your dataset again.

**Comment by fengxudi** [comment]
> Thank you for your generous sharing! Is there a paper related to this dataset so that I can cite it ?
> 
> Thanks for your dataset again.

Thank you for your enjoyment.
You can cite our dataset as follows:
H. Liu et al., "M-Gesture: Person-Independent Real-Time In-Air Gesture Recognition Using Commodity Millimeter Wave Radar," in IEEE Internet of Things Journal, doi: 10.1109/JIOT.2021.3098338.
----------------------------
Because of your suggestion, we have added the referenced methods to the Readme.
